music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show, :edit]
  resource :session, only: [:new, :create, :destroy]
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/user.rb
class User < ApplicationRecord
    validates :email, :session_token, presence: true, uniqueness: true 
    validates :password_digest, presence: true 
    validates :password, length: {minimum: 6, allow_nil: true}
    after_initialize :ensure_session_token

    def self.generate_session_token 
        SecureRandom::urlsafe_base64(16)
    end 


    def self.find_by_credentials(email, password)
        user = User.find_by(email: email)
        return nil if user.nil?
        user.is_password?(password) ? user : nil
    end 

    def reset_session_token! 
        self.session_token = User.generate_session_token
        self.save! 
        self.session_token
    end 

    def ensure_session_token
        self.session_token ||= User.generate_session_token
    end 

    def password 
        @password 
    end 

    def password=(password)
        @password = password 
        self.password_digest = BCrypt::Password.create(password)
    end 

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end 

end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def login!(user)
        @current_user = user 
        session[:session_token] = user.reset_session_token! 
    end 

    def logout! 
        current_user.reset_session_token!
        session[:session_token] = nil
    end

    def current_user 
        return nil unless session[:session_token]
        @current_user ||= User.find_by(session_token: session[:session_token])
    end 

    def logged_in?
        !!current_user
    end 

    # def require_logged_in
    #     redirect_to new_session_url unless logged_in?
    # end 

end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        @user = User.new 
        render :new
    end 

    def create 
        # debugger
        @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
        if @user 
            login!(@user)
            redirect_to user_url(@user)
        else
            flash[:errors] = ['Invalid Login Credentials']
            redirect_to new_session_url
        end 
    end 

    def destroy
        logout! 
        redirect_to new_session_url 
    end 

end 

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new  
        @user = User.new
        render :new 
    end 

    def create 
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end 
    end 

    def show 
        @user = User.find(params[:id])
        render :show
    end     

    private 
    def user_params
        params.require(:user).permit(:email, :password)
    end 
end 

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
  <% if logged_in? %>
    Welcome <%= current_user.email %>! 
  <form action="<%=session_url %>" method="post">
    <input type="hidden" name="_method" value="delete">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">
    <input type="submit" value="Log Out"> 
  <% else %>
    <a href='<%=new_session_url%>'>Log in</a> 
    <a href='<%=new_user_url%>'>Sign Up</a> 
  <% end %>
  </form>

  <h1> Music App </h1>
  </header> 

  <body>
    <%= yield %>
  </body>
</html>

music_app/app/views/users/_form.html.erb
<% if type == :new %>
<% action_url = users_url  %>
<% button_text = 'Create'%>
<% elsif type == :login %>
<% action_url = session_url %>
<% button_text = 'Login'%>
<% end %>

<ul>
<% if flash[:errors]%>
<% flash[:errors].each do |error| %>
<li>
<%= error  %>
</li>
<% end %>
<% end %>
</ul>

<h2> <%= type == :new ? "Create a new account" : "Login" %> </h2>
<form action='<%=action_url%>' method="post">
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>">

    <label for="email">
        Email:
        <input type="text" name="user[email]"  value="<%= user.email%>">
    </label>
    <br>

    <label for="password">
        Password:
        <input type="password" name="user[password]" value="<%= user.password %>">
    </label>
    <br>

    <input type="submit" value="<%= button_text %>">
</form>

music_app/app/views/users/new.html.erb
<%=render 'form', user: @user, type: :new %>